baseurl: ""

markdown: redcarpet
highlighter: pygments
permalink: /:title/

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed
